carrier - unique script
- improved logging facilities
- added info, error logging stuff

diff --git a/docker/bin/carrier b/docker/bin/carrier
--- a/docker/bin/carrier
+++ b/docker/bin/carrier
@@ -179,31 +179,31 @@ isFatalLogLevel() {
 ### logging function, designed to debug
 ### first and unique argument is the message
 debug() {
-  isDebugLogLevel && log "$1" "$GLOBAL_OPTION_LOG_OUTPUT"
+  isDebugLogLevel && log '[debug] '"$1" "$GLOBAL_OPTION_LOG_OUTPUT"
 }
 
 ### logging function, designed to info
 ### first and unique argument is the message
 info() {
-  isInfoLogLevel && log "$1" "$GLOBAL_OPTION_LOG_OUTPUT"
+  isInfoLogLevel && log '[info] '"$1" "$GLOBAL_OPTION_LOG_OUTPUT"
 }
 
 ### logging function, designed to warning
 ### first and unique argument is the message
 warning() {
-  isWarningLogLevel && log "$1" "$GLOBAL_OPTION_LOG_OUTPUT"
+  isWarningLogLevel && log '[warning] '"$1" "$GLOBAL_OPTION_LOG_OUTPUT"
 }
 
 ### logging function, designed to error
 ### first and unique argument is the message
 error() {
-  isErrorLogLevel && log "$1" "$GLOBAL_OPTION_LOG_OUTPUT"
+  isErrorLogLevel && log '[error] '"$1" "$GLOBAL_OPTION_LOG_OUTPUT"
 }
 
 ### logging function, designed to fatal
 ### first and unique argument is the message
 fatal() {
-  isFatalLogLevel && log "$1" "$GLOBAL_OPTION_LOG_OUTPUT"
+  isFatalLogLevel && log '[fatal] '"$1" "$GLOBAL_OPTION_LOG_OUTPUT"
 }
 
 ### basic usage function, shows syntax, how to use, purpose and so on...
@@ -1211,183 +1211,183 @@ initializeExecutionContext() {
 
 debugOutputExecutionContext() {
   cat << EOI
-GLOBAL_OPTION_LOG_LEVEL=\
+  GLOBAL_OPTION_LOG_LEVEL=\
 $GLOBAL_OPTION_LOG_LEVEL
-GLOBAL_OPTION_LOG_OUTPUT=\
+  GLOBAL_OPTION_LOG_OUTPUT=\
 $GLOBAL_OPTION_LOG_OUTPUT
-COMMAND=\
+  COMMAND=\
 $COMMAND
-GLOBAL_COMMAND_HELP_OPTION_MODE=\
+  GLOBAL_COMMAND_HELP_OPTION_MODE=\
 $GLOBAL_COMMAND_HELP_OPTION_MODE
-GLOBAL_COMMAND_INFO_OPTION_FORMAT=\
+  GLOBAL_COMMAND_INFO_OPTION_FORMAT=\
 $GLOBAL_COMMAND_INFO_OPTION_FORMAT
-GLOBAL_COMMAND_INSTALL_OPTION_FORCE=\
+  GLOBAL_COMMAND_INSTALL_OPTION_FORCE=\
 $GLOBAL_COMMAND_INSTALL_OPTION_FORCE
-GLOBAL_COMMAND_INSTALL_OPTION_KEEP=\
+  GLOBAL_COMMAND_INSTALL_OPTION_KEEP=\
 $GLOBAL_COMMAND_INSTALL_OPTION_KEEP
-GLOBAL_COMMAND_PACK_OPTION_FETCH_ALL_SOURCES=\
+  GLOBAL_COMMAND_PACK_OPTION_FETCH_ALL_SOURCES=\
 $GLOBAL_COMMAND_PACK_OPTION_FETCH_ALL_SOURCES
-GLOBAL_COMMAND_PACK_OPTION_ONLY_FETCH_SOURCES=\
+  GLOBAL_COMMAND_PACK_OPTION_ONLY_FETCH_SOURCES=\
 $GLOBAL_COMMAND_PACK_OPTION_ONLY_FETCH_SOURCES
-GLOBAL_COMMAND_PACK_OPTION_FETCH_SPECIFIC_IMAGE_SOURCES=\
+  GLOBAL_COMMAND_PACK_OPTION_FETCH_SPECIFIC_IMAGE_SOURCES=\
 $GLOBAL_COMMAND_PACK_OPTION_FETCH_SPECIFIC_IMAGE_SOURCES
-GLOBAL_COMMAND_UNPACK_OPTION_KEEP_SOURCES=\
+  GLOBAL_COMMAND_UNPACK_OPTION_KEEP_SOURCES=\
 $GLOBAL_COMMAND_UNPACK_OPTION_KEEP_SOURCES
-GLOBAL_COMMAND_VAGRANT_OPTION_PATH=\
+  GLOBAL_COMMAND_VAGRANT_OPTION_PATH=\
 $GLOBAL_COMMAND_VAGRANT_OPTION_PATH
-GLOBAL_COMMAND_VAGRANT_OPTION_ARGUMENTS=\
+  GLOBAL_COMMAND_VAGRANT_OPTION_ARGUMENTS=\
 $GLOBAL_COMMAND_VAGRANT_OPTION_ARGUMENTS
-DOMAIN=\
+  DOMAIN=\
 $DOMAIN
-DOMAIN_OPTIONS=\
+  DOMAIN_OPTIONS=\
 $DOMAIN_OPTIONS
-DOMAIN_BOOTSTRAP_OPTIONS=\
+  DOMAIN_BOOTSTRAP_OPTIONS=\
 $DOMAIN_BOOTSTRAP_OPTIONS
-DOMAIN_IMAGE_OPTIONS=\
+  DOMAIN_IMAGE_OPTIONS=\
 $DOMAIN_IMAGE_OPTIONS
-DOMAIN_APPLIANCE_OPTIONS=\
+  DOMAIN_APPLIANCE_OPTIONS=\
 $DOMAIN_APPLIANCE_OPTIONS
-DOMAIN_BOOTSTRAP_COMMAND_CHECK_OPTIONS=\
+  DOMAIN_BOOTSTRAP_COMMAND_CHECK_OPTIONS=\
 $DOMAIN_BOOTSTRAP_COMMAND_CHECK_OPTIONS
-DOMAIN_BOOTSTRAP_COMMAND_RUN_OPTION_RETAG_EXISTING=\
+  DOMAIN_BOOTSTRAP_COMMAND_RUN_OPTION_RETAG_EXISTING=\
 $DOMAIN_BOOTSTRAP_COMMAND_RUN_OPTION_RETAG_EXISTING
-DOMAIN_IMAGE_COMMAND_BUILD_OPTION_REMOVE_EXISTING=\
+  DOMAIN_IMAGE_COMMAND_BUILD_OPTION_REMOVE_EXISTING=\
 $DOMAIN_IMAGE_COMMAND_BUILD_OPTION_REMOVE_EXISTING
-DOMAIN_IMAGE_COMMAND_BUILD_OPTION_IMAGE_SEQUENCE=\
+  DOMAIN_IMAGE_COMMAND_BUILD_OPTION_IMAGE_SEQUENCE=\
 $DOMAIN_IMAGE_COMMAND_BUILD_OPTION_IMAGE_SEQUENCE
-DOMAIN_IMAGE_COMMAND_LIST_OPTION_LIST_ALL=\
+  DOMAIN_IMAGE_COMMAND_LIST_OPTION_LIST_ALL=\
 $DOMAIN_IMAGE_COMMAND_LIST_OPTION_LIST_ALL
-DOMAIN_IMAGE_COMMAND_LIST_OPTION_LIST_ONLY_BUILT=\
+  DOMAIN_IMAGE_COMMAND_LIST_OPTION_LIST_ONLY_BUILT=\
 $DOMAIN_IMAGE_COMMAND_LIST_OPTION_LIST_ONLY_BUILT
-DOMAIN_IMAGE_COMMAND_LIST_OPTION_LIST_ONLY_NOT_BUILT=\
+  DOMAIN_IMAGE_COMMAND_LIST_OPTION_LIST_ONLY_NOT_BUILT=\
 $DOMAIN_IMAGE_COMMAND_LIST_OPTION_LIST_ONLY_NOT_BUILT
-DOMAIN_IMAGE_COMMAND_LIST_OPTION_LIST_ONLY_LOCAL=\
+  DOMAIN_IMAGE_COMMAND_LIST_OPTION_LIST_ONLY_LOCAL=\
 $DOMAIN_IMAGE_COMMAND_LIST_OPTION_LIST_ONLY_LOCAL
-DOMAIN_IMAGE_COMMAND_LIST_OPTION_LIST_ONLY_REMOTE=\
+  DOMAIN_IMAGE_COMMAND_LIST_OPTION_LIST_ONLY_REMOTE=\
 $DOMAIN_IMAGE_COMMAND_LIST_OPTION_LIST_ONLY_REMOTE
-DOMAIN_IMAGE_COMMAND_LIST_OPTION_FORMAT=\
+  DOMAIN_IMAGE_COMMAND_LIST_OPTION_FORMAT=\
 $DOMAIN_IMAGE_COMMAND_LIST_OPTION_FORMAT
-DOMAIN_IMAGE_COMMAND_CHECK_OPTION_ALL_IMAGES=\
+  DOMAIN_IMAGE_COMMAND_CHECK_OPTION_ALL_IMAGES=\
 $DOMAIN_IMAGE_COMMAND_CHECK_OPTION_ALL_IMAGES
-DOMAIN_IMAGE_COMMAND_CHECK_OPTION_IGNORE_DATE=\
+  DOMAIN_IMAGE_COMMAND_CHECK_OPTION_IGNORE_DATE=\
 $DOMAIN_IMAGE_COMMAND_CHECK_OPTION_IGNORE_DATE
-DOMAIN_IMAGE_COMMAND_CHECK_OPTION_IGNORE_MISSING=\
+  DOMAIN_IMAGE_COMMAND_CHECK_OPTION_IGNORE_MISSING=\
 $DOMAIN_IMAGE_COMMAND_CHECK_OPTION_IGNORE_MISSING
-DOMAIN_IMAGE_COMMAND_CHECK_OPTION_IGNORE_DEPENDENCY_DEFECTS=\
+  DOMAIN_IMAGE_COMMAND_CHECK_OPTION_IGNORE_DEPENDENCY_DEFECTS=\
 $DOMAIN_IMAGE_COMMAND_CHECK_OPTION_IGNORE_DEPENDENCY_DEFECTS
-DOMAIN_IMAGE_COMMAND_CHECK_OPTION_FORMAT=\
+  DOMAIN_IMAGE_COMMAND_CHECK_OPTION_FORMAT=\
 $DOMAIN_IMAGE_COMMAND_CHECK_OPTION_FORMAT
-DOMAIN_IMAGE_COMMAND_CHECK_OPTION_IMAGE_SEQUENCE=\
+  DOMAIN_IMAGE_COMMAND_CHECK_OPTION_IMAGE_SEQUENCE=\
 $DOMAIN_IMAGE_COMMAND_CHECK_OPTION_IMAGE_SEQUENCE
-DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ALL=\
+  DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ALL=\
 $DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ALL
-DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_CONTENT=\
+  DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_CONTENT=\
 $DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_CONTENT
-DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_PROVIDES=\
+  DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_PROVIDES=\
 $DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_PROVIDES
-DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_REQUIRES=\
+  DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_REQUIRES=\
 $DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_REQUIRES
-DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_BASE=\
+  DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_BASE=\
 $DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_BASE
-DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_FETCH_IMAGE=\
+  DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_FETCH_IMAGE=\
 $DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_FETCH_IMAGE
-DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_FETCH_COMMAND=\
+  DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_FETCH_COMMAND=\
 $DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_FETCH_COMMAND
-DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_TARBALL_NAME=\
+  DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_TARBALL_NAME=\
 $DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_TARBALL_NAME
-DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_X_BUILD_DOCKERFILE=\
+  DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_X_BUILD_DOCKERFILE=\
 $DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_X_BUILD_DOCKERFILE
-DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_X_FINAL_DOCKERFILE=\
+  DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_X_FINAL_DOCKERFILE=\
 $DOMAIN_IMAGE_COMMAND_INFO_OPTION_REPORT_ONLY_X_FINAL_DOCKERFILE
-DOMAIN_IMAGE_COMMAND_INFO_OPTION_FORMAT=\
+  DOMAIN_IMAGE_COMMAND_INFO_OPTION_FORMAT=\
 $DOMAIN_IMAGE_COMMAND_INFO_OPTION_FORMAT
-DOMAIN_IMAGE_COMMAND_INFO_OPTION_IMAGE=\
+  DOMAIN_IMAGE_COMMAND_INFO_OPTION_IMAGE=\
 $DOMAIN_IMAGE_COMMAND_INFO_OPTION_IMAGE
-DOMAIN_IMAGE_COMMAND_UPGRADE_OPTION_ALL=\
+  DOMAIN_IMAGE_COMMAND_UPGRADE_OPTION_ALL=\
 $DOMAIN_IMAGE_COMMAND_UPGRADE_OPTION_ALL
-DOMAIN_IMAGE_COMMAND_UPGRADE_OPTION_IGNORE_DATE=\
+  DOMAIN_IMAGE_COMMAND_UPGRADE_OPTION_IGNORE_DATE=\
 $DOMAIN_IMAGE_COMMAND_UPGRADE_OPTION_IGNORE_DATE
-DOMAIN_IMAGE_COMMAND_UPGRADE_OPTION_IGNORE_MISSING=\
+  DOMAIN_IMAGE_COMMAND_UPGRADE_OPTION_IGNORE_MISSING=\
 $DOMAIN_IMAGE_COMMAND_UPGRADE_OPTION_IGNORE_MISSING
-DOMAIN_IMAGE_COMMAND_UPGRADE_OPTION_IGNORE_DEPENDENCY_DEFECTS=\
+  DOMAIN_IMAGE_COMMAND_UPGRADE_OPTION_IGNORE_DEPENDENCY_DEFECTS=\
 $DOMAIN_IMAGE_COMMAND_UPGRADE_OPTION_IGNORE_DEPENDENCY_DEFECTS
-DOMAIN_IMAGE_COMMAND_UPGRADE_OPTION_IMAGE_SEQUENCE=\
+  DOMAIN_IMAGE_COMMAND_UPGRADE_OPTION_IMAGE_SEQUENCE=\
 $DOMAIN_IMAGE_COMMAND_UPGRADE_OPTION_IMAGE_SEQUENCE
-DOMAIN_APPLIANCE_COMMAND_BUILD_OPTION_REMOVE_EXISTING=\
+  DOMAIN_APPLIANCE_COMMAND_BUILD_OPTION_REMOVE_EXISTING=\
 $DOMAIN_APPLIANCE_COMMAND_BUILD_OPTION_REMOVE_EXISTING
-DOMAIN_APPLIANCE_COMMAND_BUILD_OPTION_TAG_EXISTING=\
+  DOMAIN_APPLIANCE_COMMAND_BUILD_OPTION_TAG_EXISTING=\
 $DOMAIN_APPLIANCE_COMMAND_BUILD_OPTION_TAG_EXISTING
-DOMAIN_APPLIANCE_COMMAND_BUILD_OPTION_APPLIANCE_SEQUENCE=\
+  DOMAIN_APPLIANCE_COMMAND_BUILD_OPTION_APPLIANCE_SEQUENCE=\
 $DOMAIN_APPLIANCE_COMMAND_BUILD_OPTION_APPLIANCE_SEQUENCE
-DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_ALL=\
+  DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_ALL=\
 $DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_ALL
-DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_ONLY_BUILT=\
+  DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_ONLY_BUILT=\
 $DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_ONLY_BUILT
-DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_ONLY_NOT_BUILT=\
+  DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_ONLY_NOT_BUILT=\
 $DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_ONLY_NOT_BUILT
-DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_ONLY_LOCAL=\
+  DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_ONLY_LOCAL=\
 $DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_ONLY_LOCAL
-DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_ONLY_REMOTE=\
+  DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_ONLY_REMOTE=\
 $DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_ONLY_REMOTE
-DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_FORMAT=\
+  DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_FORMAT=\
 $DOMAIN_APPLIANCE_COMMAND_LIST_OPTION_FORMAT
-DOMAIN_APPLIANCE_COMMAND_CHECK_OPTION_ALL=\
+  DOMAIN_APPLIANCE_COMMAND_CHECK_OPTION_ALL=\
 $DOMAIN_APPLIANCE_COMMAND_CHECK_OPTION_ALL
-DOMAIN_APPLIANCE_COMMAND_CHECK_OPTION_IGNORE_DATE=\
+  DOMAIN_APPLIANCE_COMMAND_CHECK_OPTION_IGNORE_DATE=\
 $DOMAIN_APPLIANCE_COMMAND_CHECK_OPTION_IGNORE_DATE
-DOMAIN_APPLIANCE_COMMAND_CHECK_OPTION_IGNORE_MISSING=\
+  DOMAIN_APPLIANCE_COMMAND_CHECK_OPTION_IGNORE_MISSING=\
 $DOMAIN_APPLIANCE_COMMAND_CHECK_OPTION_IGNORE_MISSING
-DOMAIN_APPLIANCE_COMMAND_CHECK_OPTION_IGNORE_DEPENDENCY_DEFECTS=\
+  DOMAIN_APPLIANCE_COMMAND_CHECK_OPTION_IGNORE_DEPENDENCY_DEFECTS=\
 $DOMAIN_APPLIANCE_COMMAND_CHECK_OPTION_IGNORE_DEPENDENCY_DEFECTS
-DOMAIN_APPLIANCE_COMMAND_CHECK_OPTION_APPLIANCE_LIST=\
+  DOMAIN_APPLIANCE_COMMAND_CHECK_OPTION_APPLIANCE_LIST=\
 $DOMAIN_APPLIANCE_COMMAND_CHECK_OPTION_APPLIANCE_LIST
-DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_REPORT_ALL=\
+  DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_REPORT_ALL=\
 $DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_REPORT_ALL
-DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_ONLY_BASE=\
+  DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_ONLY_BASE=\
 $DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_ONLY_BASE
-DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_ONLY_CONFIG=\
+  DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_ONLY_CONFIG=\
 $DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_ONLY_CONFIG
-DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_ONLY_REQUIRES=\
+  DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_ONLY_REQUIRES=\
 $DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_ONLY_REQUIRES
-DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_ONLY_EXTRA_DOCKERFILE=\
+  DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_ONLY_EXTRA_DOCKERFILE=\
 $DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_ONLY_EXTRA_DOCKERFILE
-DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_INSPECT_ALL_SERVICES=\
+  DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_INSPECT_ALL_SERVICES=\
 $DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_INSPECT_ALL_SERVICES
-DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_INSPECT_SERVICE_LIST=\
+  DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_INSPECT_SERVICE_LIST=\
 $DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_INSPECT_SERVICE_LIST
-DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_FORMAT=\
+  DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_FORMAT=\
 $DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_FORMAT
-DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_APPLIANCE=\
+  DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_APPLIANCE=\
 $DOMAIN_APPLIANCE_COMMAND_INFO_OPTION_APPLIANCE
-DOMAIN_APPLIANCE_COMMAND_START_OPTION_BUILD=\
+  DOMAIN_APPLIANCE_COMMAND_START_OPTION_BUILD=\
 $DOMAIN_APPLIANCE_COMMAND_START_OPTION_BUILD
-DOMAIN_APPLIANCE_COMMAND_START_OPTION_APPLIANCE_SEQUENCE=\
+  DOMAIN_APPLIANCE_COMMAND_START_OPTION_APPLIANCE_SEQUENCE=\
 $DOMAIN_APPLIANCE_COMMAND_START_OPTION_APPLIANCE_SEQUENCE
-DOMAIN_APPLIANCE_COMMAND_STOP_OPTION_REMOVE_CONTAINERS=\
+  DOMAIN_APPLIANCE_COMMAND_STOP_OPTION_REMOVE_CONTAINERS=\
 $DOMAIN_APPLIANCE_COMMAND_STOP_OPTION_REMOVE_CONTAINERS
-DOMAIN_APPLIANCE_COMMAND_STOP_OPTION_APPLIANCE_SEQUENCE=\
+  DOMAIN_APPLIANCE_COMMAND_STOP_OPTION_APPLIANCE_SEQUENCE=\
 $DOMAIN_APPLIANCE_COMMAND_STOP_OPTION_APPLIANCE_SEQUENCE
-DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_LIST=\
+  DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_LIST=\
 $DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_LIST
-DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_REMOVE=\
+  DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_REMOVE=\
 $DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_REMOVE
-DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_DUMP=\
+  DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_DUMP=\
 $DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_DUMP
-DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_DUMP_PATH=\
+  DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_DUMP_PATH=\
 $DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_DUMP_PATH
-DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_VOLUME_SEQUENCE=\
+  DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_VOLUME_SEQUENCE=\
 $DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_VOLUME_SEQUENCE
-DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_APPLIANCE=\
+  DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_APPLIANCE=\
 $DOMAIN_APPLIANCE_COMMAND_VOLUMES_OPTION_APPLIANCE
-DOMAIN_APPLIANCE_COMMAND_UPGRADE_OPTION_ALL=\
+  DOMAIN_APPLIANCE_COMMAND_UPGRADE_OPTION_ALL=\
 $DOMAIN_APPLIANCE_COMMAND_UPGRADE_OPTION_ALL
-DOMAIN_APPLIANCE_COMMAND_UPGRADE_OPTION_IGNORE_DATE=\
+  DOMAIN_APPLIANCE_COMMAND_UPGRADE_OPTION_IGNORE_DATE=\
 $DOMAIN_APPLIANCE_COMMAND_UPGRADE_OPTION_IGNORE_DATE
-DOMAIN_APPLIANCE_COMMAND_UPGRADE_OPTION_IGNORE_MISSING=\
+  DOMAIN_APPLIANCE_COMMAND_UPGRADE_OPTION_IGNORE_MISSING=\
 $DOMAIN_APPLIANCE_COMMAND_UPGRADE_OPTION_IGNORE_MISSING
-DOMAIN_APPLIANCE_COMMAND_UPGRADE_OPTION_IGNORE_DEPENDENCY_DEFECTS=\
+  DOMAIN_APPLIANCE_COMMAND_UPGRADE_OPTION_IGNORE_DEPENDENCY_DEFECTS=\
 $DOMAIN_APPLIANCE_COMMAND_UPGRADE_OPTION_IGNORE_DEPENDENCY_DEFECTS
-DOMAIN_APPLIANCE_COMMAND_UPGRADE_OPTION_APPLIANCE_SEQUENCE=\
+  DOMAIN_APPLIANCE_COMMAND_UPGRADE_OPTION_APPLIANCE_SEQUENCE=\
 $DOMAIN_APPLIANCE_COMMAND_UPGRADE_OPTION_APPLIANCE_SEQUENCE
 EOI
 }
@@ -1779,12 +1779,16 @@ buildExecutionContextFromArguments() {
 ### helper function executing the help command with its options if required
 executeHelpCommand() {
   if [ "$COMMAND" = 'help' ]; then
+    info 'help command has been requested'
     local mode="$GLOBAL_COMMAND_HELP_OPTION_MODE"
     [ "$mode" = '-H' ] || [ "$mode" = '--full' ]
     local fullMode=$?
+    [ "$fullMode" -eq 0 ] \
+    && info 'full mode help requested' \
+    || info 'brief mode help requested'
     [ "$fullMode" -eq 0 ] && usageFull || usage
   else
-    # help is not the requested command
+    warning 'help was not the requested command'
     return 1
   fi
 }
@@ -1834,13 +1838,16 @@ executeBootstrapCheckCommand() {
 ### execute the check command of the bootstrap domain
 executeBootstrapRunCommand() {
   # TODO handle options, draft version
-  [ "$DOMAIN" = 'bootstrap' ] \
-  && [ "$COMMAND" = 'run' ] \
-  && ( exec "${CARRIER_LIB_DIR}"/carrier-bootstrap )
+  local executionResult=1
 
-  local executionResult=$?
+  if [ "$DOMAIN" = 'bootstrap' ] \
+     && [ "$COMMAND" = 'run' ]; then
+    info 'bootstrap run requested, starting it in a subshell'
+    ( exec "${CARRIER_LIB_DIR}"/carrier-bootstrap )
+    executionResult=$?
+  fi
 
-  debug '*** executeBootstrapRunCommand() Result'
+  debug 'executeBootstrapRunCommand() Result'
   [ $executionResult -eq 0 ] \
   && debug 'execution succeeded' \
   || debug 'execution failed'
@@ -1854,10 +1861,15 @@ executeImageBuildCommand() {
   if [ ! "$DOMAIN" = 'image' ] \
      || [ ! "$COMMAND" = 'build' ] \
      || [ -z "$DOMAIN_IMAGE_COMMAND_BUILD_OPTION_IMAGE_SEQUENCE" ]; then
+    error "incomplete or incorrect execution context:
+  DOMAIN=$DOMAIN
+  COMMAND=$COMMAND
+  DOMAIN_IMAGE_COMMAND_BUILD_OPTION_IMAGE_SEQUENCE=\
+$DOMAIN_IMAGE_COMMAND_BUILD_OPTION_IMAGE_SEQUENCE"
     return 1
   fi
 
-  # the sequence is comma separated, get it space separated
+  info 'splitting provided sequence using space character'
   local sequence="$(
     splitSequence \
     "$DOMAIN_IMAGE_COMMAND_BUILD_OPTION_IMAGE_SEQUENCE" \
@@ -1866,10 +1878,16 @@ executeImageBuildCommand() {
 
   # build each image in the sequence, calling the right script in a subshell
   local image=
+  local executionResult=1
   for image in $sequence; do
     # the first image build failing return from that function
-    ( exec "${CARRIER_LIB_DIR}"/carrier-build-image "$image" ) \
-    || return 1
+    ( exec "${CARRIER_LIB_DIR}"/carrier-build-image "$image" )
+    executionResult=$?
+
+    if [ $executionResult -ne 0 ]; then
+      error 'Failed to build the requested '"$image"' image.'
+      return $executionResult
+    fi
   done
 }
 
@@ -2020,7 +2038,7 @@ executeBootstrapCommand() {
 
   local executionResult=$?
 
-  debug '*** executeBootstrapCommand() Result'
+  debug 'executeBootstrapCommand() Result'
   [ $executionResult -eq 0 ] \
   && debug 'execution succeeded' \
   || debug 'execution failed'
@@ -2038,7 +2056,7 @@ executeImageCommand() {
 
   local executionResult=$?
 
-  debug '*** executeImageCommand() Result'
+  debug 'executeImageCommand() Result'
   [ $executionResult -eq 0 ] \
   && debug 'execution succeeded' \
   || debug 'execution failed'
@@ -2061,7 +2079,7 @@ executeApplianceCommand() {
 
   local executionResult=$?
 
-  debug '*** executeApplianceCommand() Result'
+  debug 'executeApplianceCommand() Result'
   [ $executionResult -eq 0 ] \
   && debug 'execution succeeded' \
   || debug 'execution failed'
@@ -2082,7 +2100,7 @@ executeGlobalCommand() {
 
   local executionResult=$?
 
-  debug '*** executeGlobalCommand() Result'
+  debug 'executeGlobalCommand() Result'
   [ $executionResult -eq 0 ] \
   && debug 'execution succeeded' \
   || debug 'execution failed'
@@ -2100,7 +2118,7 @@ executeDomainCommand() {
 
   local executionResult=$?
 
-  debug '*** executeDomainCommand() Result'
+  debug 'executeDomainCommand() Result'
   [ $executionResult -eq 0 ] \
   && debug 'execution succeeded' \
   || debug 'execution failed'
@@ -2127,7 +2145,7 @@ fi
 ### Once the execution context is set, execute the script using it. As the
 ### execution context is verified when set, one function must succeed
 executeWithContext() {
-  debug "*** Execution Context
+  debug "Execution Context:
 $(debugOutputExecutionContext)"
 
   executeGlobalCommand \
@@ -2135,7 +2153,7 @@ $(debugOutputExecutionContext)"
 
   local executionResult=$?
 
-  debug '*** executeWithContext() Result'
+  debug 'executeWithContext() Result'
   [ $executionResult -eq 0 ] \
   && debug 'execution succeeded' \
   || debug 'execution failed'
