docker
- build tools: fully implemented import and export package for images
- m4 uses this system

diff --git a/docker/01-build-tools/exportPackageTo b/docker/01-build-tools/exportPackageTo
--- a/docker/01-build-tools/exportPackageTo
+++ b/docker/01-build-tools/exportPackageTo
@@ -14,4 +14,9 @@ mkdir -p "$package_directory"
 tar \
   -cf "$package_directory"/"$package_file_name" \
   --no-recursion \
-  $(cat /image.dist)
+  $(cat /image.dist) 2> /dev/null
+
+if [ ! $? -eq 0 ]; then
+  echo 'Error while creating package...exiting...'
+  exit 1
+fi
